<?php

/**
 * PluginNewRelicLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNewRelicLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginNewRelicLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginNewRelicLog');
    }
}