<?php

/**
 * PluginNewRelicLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfNewRelicPlugin
 * @subpackage model
 * @author     Robin Corps <robin@wirehive.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginNewRelicLog extends BaseNewRelicLog
{

}