NewRelicLog:
  actAs:
    Timestampable:  ~
  columns:
    api:              { type: string(50) }
    method:           { type: string(50) }
    url:              { type: string(255) }
    content_sent:     { type: clob }
    content_received: { type: clob }